### PR TITLE
Use ephemeris release version

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by natefoo** [comment]
@galaxybot deploy this

**Comment by natefoo** [comment]
@galaxybot deploy this

**Comment by natefoo** [comment]
galaxy-db-02 was joined to the tailnet as `localhost-1`, I fixed this (manually for now).

**Comment by natefoo** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by natefoo** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by natefoo** [comment]
Probably memory since it's using the default ~ 3GB, but a wholly unhelpful error message:
```
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
rsync_from_ncbi.pl: unexpected FTP path (new server?) for https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/762/265/GCF_000762265.1_ASM76226v1
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_build_kraken2_database/e4b4837f06f5/data_manager_build_kraken2_database/data_manager/kraken2_build_database.py", line 477, in <module>
    main()
  File "/cvmfs/main.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_build_kraken2_database/e4b4837f06f5/data_manager_build_kraken2_database/data_manager/kraken2_build_database.py", line 426, in main
    target_directory,
  File "/cvmfs/main.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_build_kraken2_database/e4b4837f06f5/data_manager_build_kraken2_database/data_manager/kraken2_build_database.py", line 107, in kraken2_build_standard
    subprocess.check_call(['kraken2-build'] + args, cwd=target_directory)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['kraken2-build', '--threads', '1', '--standard', '--kmer-len', '35', '--minimizer-len', '31', '--minimizer-spaces', '6', '--load-factor', '0.7', '--db', '2024-02-05T150339Z_standard_kmer-len_35_minimizer-len_31_minimizer-spaces_6_load-factor_0.7']' returned non-zero exit status 22.
```

**Comment by natefoo** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Pull request merged**
